# Generated by Django 5.1.1 on 2024-09-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_timestamp_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='user',
            new_name='creator',
        ),
    ]
